import { StyleSheet } from 'react-native';
export const buttonStyles = StyleSheet.create({
  wooden: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginVertical: 10,
    borderRadius: 10,
  },
  woodenText: {
    fontSize: 18,
    lineHeight: 22,
    color: '#16356a',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 5,
    textShadowColor: 'white',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  woodenTitle: {
    fontSize: 36,
    lineHeight: 40,
    color: '#16356a',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 10,
    textShadowColor: 'white',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  woodenTitleGreen: {
    fontSize: 36,
    lineHeight: 40,
    color: '#16356a',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 10,
    textShadowColor: 'white',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
});
